TrainingArguments:
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  evaluation_strategy: epoch   
  eval_steps: 500              
  save_strategy: epoch         
  save_steps: 1000000          
  learning_rate: 5e-5
  warmup_steps: 50
  weight_decay: 0.01
  logging_steps: 20
  fp16: true
  gradient_accumulation_steps: 2
  predict_with_generate: true
  load_best_model_at_end: true
  metric_for_best_model: eval_loss
  report_to: none