artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://github.com/ThisLonzoBall/Research-Summarizer/raw/main/Summarizer-Dataset.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/my_dataset
  tokenizer_name: google/pegasus-cnn_dailymail
